#!/usr/bin/env bash
# Build the Go/Python/Rust drivers and run a hyperfine matrix comparing this
# library against Python's stdlib itertools (plus sympy/more-itertools for the
# partition ops) and the Rust itertools crate. Writes the results, with pinned
# versions and caveats, to bench/RESULTS.md.
#
# See issue #8.
set -euo pipefail

bench_dir="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
repo_dir="$(cd "$bench_dir/.." && pwd)"
bin_dir="$bench_dir/bin"
results="$bench_dir/RESULTS.md"
mkdir -p "$bin_dir"

go_bin="$bin_dir/go-driver"
rust_bin="$bench_dir/rust/target/release/rust-driver"
py_driver="$bench_dir/py/driver.py"

echo "==> Building Go driver"
(cd "$repo_dir" && go build -o "$go_bin" ./bench/go)

echo "==> Building Rust driver (--release)"
cargo build --release --manifest-path "$bench_dir/rust/Cargo.toml" --quiet

# Python venv with the partition-op dependencies (sympy, more-itertools).
# Using a prebuilt venv's interpreter directly keeps uv/pip out of the timed
# commands.
venv="$bin_dir/.venv"
if [[ ! -x "$venv/bin/python" ]]; then
    echo "==> Creating Python venv with sympy + more-itertools"
    if command -v uv >/dev/null; then
        uv venv --quiet "$venv"
        uv pip install --quiet --python "$venv/bin/python" sympy more-itertools
    else
        python3 -m venv "$venv"
        "$venv/bin/pip" install --quiet sympy more-itertools
    fi
fi
py="$venv/bin/python"

# Workload matrix: "op args...". Sized so Python interpreter startup is
# negligible relative to the iteration cost.
workloads=(
    "combinations 26 12"
    "cwr 20 10"
    "permutations 11 8"
    "product 10 7"
    "powerset 22"
    "productof 10 9 8 7 6 5 4 3"
    "intpartitions 65"
    "setpartitions 11"
)

# Versions, pinned for reproducibility.
go_ver="$(go version | awk '{print $3}')"
py_ver="$("$py" --version | awk '{print $2}')"
rust_ver="$(rustc --version | awk '{print $2}')"
itertools_ver="$(awk '/^name = "itertools"/{f=1} f&&/^version =/{gsub(/"/,"",$3); print $3; exit}' "$bench_dir/rust/Cargo.lock")"
sympy_ver="$("$py" -c 'import sympy; print(sympy.__version__)')"
more_itertools_ver="$("$py" -c 'import more_itertools; print(more_itertools.__version__)')"

tmp="$(mktemp -d)"
trap 'rm -rf "$tmp"' EXIT

# emit_mermaid <hyperfine-json> <title> prints a GitHub-native mermaid
# xychart-beta bar chart of the mean wall-clock time (ms) per command. Mermaid
# bar charts are single-series, so this is one chart per workload.
emit_mermaid() {
    "$py" - "$1" "$2" <<'PY'
import json, sys

with open(sys.argv[1]) as f:
    results = json.load(f)["results"]
title = sys.argv[2]

# hyperfine writes results in the order the commands were passed; -n names
# land in the "command" field.
names = [r["command"].replace("()", "") for r in results]
means_ms = [r["mean"] * 1000 for r in results]
ymax = max(means_ms) * 1.1

print("```mermaid")
print("xychart-beta")
print(f'    title "{title} (mean ms, lower is better)"')
print("    x-axis [" + ", ".join(f'"{n}"' for n in names) + "]")
print(f'    y-axis "milliseconds" 0 --> {ymax:.0f}')
print("    bar [" + ", ".join(f"{m:.1f}" for m in means_ms) + "]")
print("```")
PY
}

# Process-startup floors: bare interpreter, and interpreter + sympy import
# (the practical lower bound for the intpartitions Python row).
echo "==> Measuring Python startup floors"
hyperfine --warmup 3 --export-markdown "$tmp/floor.md" -N \
    -n "python -c pass" "$py -c pass" \
    -n "python -c 'import sympy'" "$py -c 'import sympy'" >/dev/null

# RESULTS.md header.
{
    echo "# Cross-language benchmark results"
    echo
    echo "Whole-process wall-clock comparison of this Go library against Python's"
    echo "stdlib \`itertools\` and the Rust \`itertools\` crate, measured with"
    echo "[hyperfine](https://github.com/sharkdp/hyperfine). Generated by"
    echo "\`bench/run.sh\` ($(date -u +%Y-%m-%dT%H:%M:%SZ))."
    echo
    echo "## Versions"
    echo
    echo "| Tool | Version |"
    echo "|------|---------|"
    echo "| Go | $go_ver |"
    echo "| Python | $py_ver |"
    echo "| Rust | $rust_ver |"
    echo "| itertools crate | $itertools_ver |"
    echo "| sympy | $sympy_ver |"
    echo "| more-itertools | $more_itertools_ver |"
    echo "| hyperfine | $(hyperfine --version | awk '{print $2}') |"
    echo
    echo "## Caveats"
    echo
    echo "- **Apples-to-oranges allocation.** Go \`All()\`, Python \`itertools\`, and"
    echo "  the Rust \`itertools\` crate all allocate a fresh tuple/Vec per item, so"
    echo "  those three are the fair comparison. Go \`AllBorrowed()\` reuses an"
    echo "  internal buffer and has no direct analog in the other two — it is the"
    echo "  library's low-allocation fast path, shown here for reference."
    echo "- **Partitions have no itertools analog.** For \`intpartitions\` Python"
    echo "  uses \`sympy\` and for \`setpartitions\` it uses \`more-itertools\`; the"
    echo "  Rust \`itertools\` crate has neither, so the Rust rows for those two"
    echo "  workloads are small hand-rolled generators mirroring this library's"
    echo "  algorithms — they benchmark \"what a Rust programmer would write\","
    echo "  not an ecosystem library. The Rust setpartitions generator also only"
    echo "  walks the block assignments (like Go \`AllBorrowed()\`), while Python"
    echo "  more-itertools and Go \`All()\` materialize the blocks themselves."
    echo "- **Startup overhead.** A static Go/Rust binary starts far faster than the"
    echo "  Python interpreter. Workloads are sized so iteration dominates; the"
    echo "  Python startup floors below are the practical lower bounds for the"
    echo "  Python rows (\`import sympy\` applies to the intpartitions row)."
    echo "- Each driver iterates the full sequence and sum-accumulates a"
    echo "  data-dependent value per item (wrapping 64-bit) to defeat dead-code"
    echo "  elimination; all drivers print the same accumulator for a given"
    echo "  workload. Index ops sum every index, intpartitions sums every part,"
    echo "  and setpartitions sums \`assignment[i] * i\` over the canonical"
    echo "  restricted-growth-string block assignment."
    echo
    echo "### Python startup floors"
    echo
    cat "$tmp/floor.md"
    echo
    echo "## Workloads"
} >"$results"

run=0
for w in "${workloads[@]}"; do
    read -r op rest <<<"$w"
    run=$((run + 1))
    out="$tmp/run_$run.md"

    label="$op $rest"
    py_cmd="$py $py_driver $op $rest"
    rust_cmd="$rust_bin $op $rest"
    go_all="$go_bin $op $rest"
    go_borrowed="$go_bin --borrowed $op $rest"

    json="$tmp/run_$run.json"
    echo "==> Benchmarking $label"
    hyperfine --warmup 3 --export-markdown "$out" --export-json "$json" \
        -n "Python" "$py_cmd" \
        -n "Rust" "$rust_cmd" \
        -n "Go All()" "$go_all" \
        -n "Go AllBorrowed()" "$go_borrowed"

    {
        echo
        echo "### $label"
        echo
        emit_mermaid "$json" "$label"
        echo
        cat "$out"
    } >>"$results"
done

echo "==> Wrote $results"
