#!/usr/bin/env bash
# Build the Go/Python/Rust drivers and run a hyperfine matrix comparing this
# library against Python's stdlib itertools and the Rust itertools crate.
# Writes the results, with pinned versions and caveats, to bench/RESULTS.md.
#
# See issue #8.
set -euo pipefail

bench_dir="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
repo_dir="$(cd "$bench_dir/.." && pwd)"
bin_dir="$bench_dir/bin"
results="$bench_dir/RESULTS.md"
mkdir -p "$bin_dir"

go_bin="$bin_dir/go-driver"
rust_bin="$bench_dir/rust/target/release/rust-driver"
py_driver="$bench_dir/py/driver.py"

echo "==> Building Go driver"
(cd "$repo_dir" && go build -o "$go_bin" ./bench/go)

echo "==> Building Rust driver (--release)"
cargo build --release --manifest-path "$bench_dir/rust/Cargo.toml" --quiet

# Workload matrix: "op n k" (k empty for powerset). Sized so Python interpreter
# startup is negligible relative to the iteration cost.
workloads=(
    "combinations 26 12"
    "cwr 20 10"
    "permutations 11 8"
    "product 10 7"
    "powerset 22"
)

# Versions, pinned for reproducibility.
go_ver="$(go version | awk '{print $3}')"
py_ver="$(python3 --version | awk '{print $2}')"
rust_ver="$(rustc --version | awk '{print $2}')"
itertools_ver="$(awk '/^name = "itertools"/{f=1} f&&/^version =/{gsub(/"/,"",$3); print $3; exit}' "$bench_dir/rust/Cargo.lock")"

tmp="$(mktemp -d)"
trap 'rm -rf "$tmp"' EXIT

# Process-startup floor: bare Python interpreter, no imports.
echo "==> Measuring Python startup floor"
hyperfine --warmup 3 --export-markdown "$tmp/floor.md" -N 'python3 -c pass' >/dev/null

# RESULTS.md header.
{
    echo "# Cross-language benchmark results"
    echo
    echo "Whole-process wall-clock comparison of this Go library against Python's"
    echo "stdlib \`itertools\` and the Rust \`itertools\` crate, measured with"
    echo "[hyperfine](https://github.com/sharkdp/hyperfine). Generated by"
    echo "\`bench/run.sh\` ($(date -u +%Y-%m-%dT%H:%M:%SZ))."
    echo
    echo "## Versions"
    echo
    echo "| Tool | Version |"
    echo "|------|---------|"
    echo "| Go | $go_ver |"
    echo "| Python | $py_ver |"
    echo "| Rust | $rust_ver |"
    echo "| itertools crate | $itertools_ver |"
    echo "| hyperfine | $(hyperfine --version | awk '{print $2}') |"
    echo
    echo "## Caveats"
    echo
    echo "- **Apples-to-oranges allocation.** Go \`All()\`, Python \`itertools\`, and"
    echo "  the Rust \`itertools\` crate all allocate a fresh tuple/Vec per item, so"
    echo "  those three are the fair comparison. Go \`AllBorrowed()\` reuses an"
    echo "  internal buffer and has no direct analog in the other two — it is the"
    echo "  library's low-allocation fast path, shown here for reference."
    echo "- **Startup overhead.** A static Go/Rust binary starts far faster than the"
    echo "  Python interpreter. Workloads are sized so iteration dominates; the"
    echo "  Python startup floor below is the practical lower bound for the Python"
    echo "  rows."
    echo "- Each driver iterates the full sequence and sum-accumulates every index"
    echo "  (wrapping 64-bit) to defeat dead-code elimination; all drivers print the"
    echo "  same accumulator for a given (op, n, k)."
    echo
    echo "### Python startup floor"
    echo
    cat "$tmp/floor.md"
    echo
    echo "## Workloads"
} >"$results"

run=0
for w in "${workloads[@]}"; do
    read -r op n k <<<"$w"
    run=$((run + 1))
    out="$tmp/run_$run.md"

    if [[ "$op" == "powerset" ]]; then
        label="$op n=$n"
        py_cmd="python3 $py_driver $op $n"
        rust_cmd="$rust_bin $op $n"
        go_all="$go_bin $op $n"
        go_borrowed="$go_bin --borrowed $op $n"
    else
        label="$op n=$n k=$k"
        py_cmd="python3 $py_driver $op $n $k"
        rust_cmd="$rust_bin $op $n $k"
        go_all="$go_bin $op $n $k"
        go_borrowed="$go_bin --borrowed $op $n $k"
    fi

    echo "==> Benchmarking $label"
    hyperfine --warmup 3 --export-markdown "$out" \
        -n "Python itertools" "$py_cmd" \
        -n "Rust itertools" "$rust_cmd" \
        -n "Go All()" "$go_all" \
        -n "Go AllBorrowed()" "$go_borrowed"

    {
        echo
        echo "### $label"
        echo
        cat "$out"
    } >>"$results"
done

echo "==> Wrote $results"
